In [6]:
import pandas as pd

caminho = "../data/processed/nascidos_vivos_ce.csv"

df_preview = pd.read_csv(caminho, dtype=str, nrows=1000)
df_preview.head(1000)

,ARQUIVO_ORIGEM,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,...,TPDOCRESP,DTDECLARAC,ESCMAEAGR1,STDNEPIDEM,STDNNOVA,CODPAISRES,TPROBSON,PARIDADE,KOTELCHUCK,CONTADOR
0,DNCE2025,1,6205224,110020,1,42,2,5,848310,NaN,...,3,06052025,08,1,1,1,08,0,5,7185
1,DNCE2025,1,6205224,110020,1,42,2,5,223505,NaN,...,3,06052025,08,1,1,1,08,0,5,7186
2,DNCE2025,1,9917322,150140,1,32,1,4,411010,01,...,4,09022025,12,1,1,1,10,1,5,69445
3,DNCE2025,1,2329905,150680,1,21,1,4,999992,00,...,3,23062025,05,1,1,1,01,0,5,110566
4,DNCE2025,1,2463016,210005,1,25,1,4,999992,02,...,4,05052025,06,1,1,1,11,1,2,134831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,DNCE2025,1,9275134,230030,1,17,5,4,612005,00,...,0,27032025,05,1,1,1,03,1,5,201770
996,DNCE2025,1,9275134,230030,1,37,5,4,612005,01,...,0,26032025,06,1,1,1,05,1,9,201771
997,DNCE2025,1,9275134,230030,1,15,5,4,999991,00,...,0,24032025,04,1,1,1,01,0,5,201772
998,DNCE2025,1,9275134,230030,1,30,1,4,999993,00,...,0,25032025,06,1,1,1,03,1,5,201773
999,DNCE2025,1,9275134,230030,1,26,5,4,612005,03,...,0,26032025,04,1,1,1,03,1,5,201774

In [13]:
import pandas as pd

caminho = "../data/processed/nascidos_vivos_ce.csv"

df = pd.read_csv(caminho)

#Remove linhas completamente vazias(se não me engano são só duas)
df_limpo = df.dropna(how='all', axis=0)

df_limpo.head(200000)

,ARQUIVO_ORIGEM,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,...,TPDOCRESP,DTDECLARAC,ESCMAEAGR1,STDNEPIDEM,STDNNOVA,CODPAISRES,TPROBSON,PARIDADE,KOTELCHUCK,CONTADOR
0,DNCE2025,1,6205224.0,110020,1,42,2.0,5.0,848310.0,NaN,...,3.0,6052025.0,8.0,1.0,1,1.0,8,0,5,7185
1,DNCE2025,1,6205224.0,110020,1,42,2.0,5.0,223505.0,NaN,...,3.0,6052025.0,8.0,1.0,1,1.0,8,0,5,7186
2,DNCE2025,1,9917322.0,150140,1,32,1.0,4.0,411010.0,1.0,...,4.0,9022025.0,12.0,1.0,1,1.0,10,1,5,69445
3,DNCE2025,1,2329905.0,150680,1,21,1.0,4.0,999992.0,0.0,...,3.0,23062025.0,5.0,1.0,1,1.0,1,0,5,110566
4,DNCE2025,1,2463016.0,210005,1,25,1.0,4.0,999992.0,2.0,...,4.0,5052025.0,6.0,1.0,1,1.0,11,1,2,134831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142563,DNCE2026,1,2748568.0,351040,1,29,1.0,5.0,999992.0,0.0,...,3.0,12052026.0,7.0,1.0,1,1.0,2,0,4,509708
142564,DNCE2026,1,2079542.0,355030,1,36,2.0,5.0,241005.0,1.0,...,3.0,18032026.0,8.0,1.0,1,1.0,7,1,3,633419
142565,DNCE2026,1,2079828.0,355280,1,26,1.0,4.0,521110.0,0.0,...,3.0,2052026.0,6.0,1.0,1,1.0,10,0,5,664998
142566,DNCE2026,1,2223538.0,430510,1,33,5.0,5.0,354705.0,0.0,...,3.0,8032026.0,8.0,1.0,1,1.0,6,0,3,771390
142567,DNCE2026,1,7539797.0,530010,1,32,2.0,5.0,111405.0,0.0,...,5.0,13042026.0,8.0,1.0,1,1.0,1,0,5,880866